export default {
  ROLE_STUDENT: "ROLE_STUDENT",
  ROLE_ADMIN: "ROLE_ADMIN",
  ROLE_ALL: "ROLE_ALL",

  STATUS_NOT_START: "STATUS_NOT_START",
  STATUS_NOT_START_ZH: "未开始",
  STATUS_STARTED: "STATUS_STARTED",
  STATUS_STARTED_ZH: "答题中",
  STATUS_SUBMITTED: "STATUS_SUBMITTED",
  STATUS_SUBMITTED_ZH: "已提交"
};
