export default {
  ROLE_STUDENT: "ROLE_STUDENT",
  ROLE_ADMIN: "ROLE_ADMIN",
  ROLE_ALL: "ROLE_ALL",

  STATUS_NOT_START: "STATUS_NOT_START",
  STATUS_NOT_START_ZH: "未开始",
  STATUS_GENERATED: "STATUS_GENERATED",
  STATUS_GENERATED_ZH: "未开始", // 前端不必在页面上展现 STATUS_NOT_START 和 STATUS_GENERATED 的区别
  STATUS_STARTED: "STATUS_STARTED",
  STATUS_STARTED_ZH: "答题中",
  STATUS_SUBMITTED: "STATUS_SUBMITTED",
  STATUS_SUBMITTED_ZH: "已提交",

  TIME_LIMIT: 30 * 60 * 1000,
  CHOICE_QUESTION_NUM: 20,
  JUDGE_QUESTION_NUM: 10,
  CHOICE_QUESTION_SCORE: 4,
  JUDGE_QUESTION_SCORE: 2
};
